version: 2

sources:
  - name: retail_raw
    database: ANALYTICS
    schema: DBT_GVIJAYAN

    tables:
      - name: CUSTOMERS_RAW
      - name: PRODUCTS_RAW
      - name: STORES_RAW
      - name: EMPLOYEES_RAW
      - name: PROMOTIONS_RAW
      - name: ORDERS_RAW
      - name: ORDER_ITEMS_RAW
      - name: RETURNS_RAW